name: Build and Export

on:
  workflow_dispatch:
    inputs:
      git_version:
        description: 'Git version to build (e.g., 2.52.0.windows.1)'
        required: true
        default: '2.52.0.windows.1'
        type: string


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gettext zip wget apt-transport-https software-properties-common
        wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y powershell

    - name: Run the build script
      env:
        # https://github.com/git-for-windows/git/archive/refs/tags/v2.52.0.windows.1.tar.gz
        # Settings -> Secrets and variables -> Actions 添加一个变量 GIT_VERSION 并指定版本号，如：2.52.0.windows.1
        # GIT_VERSION: ${{ secrets.GIT_VERSION }}
        GIT_VERSION: ${{ github.event.inputs.git_version }}
      run: |
        chmod +x ./build.sh
        ./build.sh ${{ env.GIT_VERSION }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ZIP_FILE }}
        path: ${{ env.ZIP_FILE }}

